### ISSUE TITLE
On brave, when clicking "View" or "View Article" even though submission compilation was successful, Brave displays "corrupt PDF"

### ISSUE THREAD

**Issue by TimDaub** [arXiv/arxiv-submission-core#79]
**Describe the bug**
On brave, when clicking "View" or "View Article" even though submission compilation was successful, Brave displays "corrupt PDF"

**To Reproduce**
1. Download brave browser
2. Submit a working paper to arxiv
3. Click on "View" (Process) or "View Article" (Preview)
4. PDF will not render. Try same with fresh Installation of Firefox. It works.

**Expected behavior**
All browsers should work equally.

**Desktop (please complete the following information):**
Brave: Version 0.63.55 Chromium: 74.0.3729.131 (Official Build) (64-bit)

**Comment by jweiskoff** [comment]
Please direct this issue to help@arxiv.org citing the specific submit-id for assistance.
