### ISSUE TITLE
Submitting LaTeX-produced publisher PDF files of open-access papers

### ISSUE THREAD

**Issue by episanty** [arXiv/arxiv-submission-core#80]
Use case:

> I am an author of a paper published under a Creative Commons license in an Open Access journal, and I would like to deposit the Version of Record of the paper into arXiv, as allowed by the license. All I have available for this is the PDF file itself, and I do not have access to the source used by the publisher to produce the VoR.

For some publishers (e.g. APS) this seems to work fine, but for some others (including IOP) the publisher-produced PDF triggers the arXiv warnings against submitting PDF files produced from LaTeX, and requests the LaTeX source for the document.

Now, I fully understand and support the decision to require TeX source wherever it is available, but in this specific case (which, I would argue, should become more common), the submitter does not have the source available. Of course, one can argue that posting to arXiv is not *necessary* as such, strictly speaking, since the paper is already freely available elsewhere, but it is definitely odd that, having removed the hurdle of copyright restrictions, one cannot submit to arXiv because of the LaTeX detector.

As such, it would be good if the processing system can detect these cases, or allow the user to declare them (possibly going through manual review?), and allow the authors to submit the PDF on its own.

(Apologies if I have posted this in the wrong place -- if that's the case, please direct me to the correct venue!)

**Comment by jweiskoff** [comment]
Please direct this issue to help@arxiv.org as this is not the correct venue for help-desk inquiries.

**Comment by episanty** [comment]
@jweiskoff I have emailed them already, and I agree that this is not the correct venue for individual-case handling.

But I would argue that the use case is more general, and it should at least be considered explicitly. Is arXiv closed to the notion of being a place where VoRs can be deposited? If so, what is the rationale? If not, shouldn't that be implemented in practice?

**Comment by jweiskoff** [comment]
VoR may be accepted, but it is greatly effected by the copyright assigned to the work. While open access is obviously preferred, it is not (yet) the norm for journals. It is my impression that journals whose complete corpus is open access are not yet common enough for us to extend the development effort required to determine this (and could be easily gamed, which is exceedingly common for our users). 
We do accept open access pdf when alerted to us by the submitter (or if they pass through the pdf from tex checks), but at this time I don't expect this to be a development priority.
